version: '3.0'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"

  atour-backend:
    depends_on:
      - db
    build: atour-backend
    ports:
      - "8081:8081"
    restart: always

