version: '3.0'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"

  atour-backend:
    depends_on:
      - db
    build: atour-backend
    ports:
      - "3000:3000"
    restart: always

  atour-frontend:
    depends_on:
      - atour-backend
    build: atour-frontend
    ports:
      - "8000:80"
    environment: 
      - API_ENDPOINT=atour-backend
    restart: always
